spring:
  profiles:
    active: ${eureka.instance.hostname}
  application:
    name: eureka-server
server:
  port: 8053
  next-port: 8051
eureka:
  instance:
    hostname: zone-s3
    hostname-s: zone-s1
  client:
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname-s}:${server.next-port}/eureka/
