spring:
#  profiles:
#    active: ${eureka.instance.hostname}
  application:
    name: eureka-server
server:
  port: 8053
  next-port: 8051
eureka:
#  instance:
#    hostname: zone-s3
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.next-port}/eureka/
