server:
  port: 8040
  eureka-port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.eureka-port}/eureka/
spring:
  profiles:
    active: native
  application:
    name: microservice-server
  cloud:
    config:
      server:
        native:
           search-locations: file:/Users/zhoumeng/amuzhou/idea/amuzhou/spring-cloud-study/config-repo